logging.level.com.vylla.rental: DEBUG

server:
  port: 9000
  contextPath: /rental

spring:
  data:
    mongodb:
      uri: mongodb://192.168.99.100:27017/rental
  kafka:
    bootstrap-servers: ${kafka.bootstrap.servers}
    producer:
      enabled: true

kafka.bootstrap.servers: http://127.0.0.1:9092

