security.basic.enabled: false

logging.level.com.matias.rental: DEBUG

server:
  port: 9000

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/rental

#  kafka:
#    bootstrap-servers: ${kafka.bootstrap.servers}
#    producer:
#      enabled: true
#
#kafka.bootstrap.servers: http://127.0.0.1:9092
